// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNVJeid3Vw2idupTrQvChy_Fl0tu-YSSU',
    appId: '1:63605957686:web:d4552ee97c66d02d99a497',
    messagingSenderId: '63605957686',
    projectId: 'royale-moments',
    authDomain: 'royale-moments.firebaseapp.com',
    storageBucket: 'royale-moments.firebasestorage.app',
    measurementId: 'G-NK5RHB75MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Ui1650azOyLDklcOa-Q81GUcDtU6-V0',
    appId: '1:63605957686:android:689436a8cb480d0a99a497',
    messagingSenderId: '63605957686',
    projectId: 'royale-moments',
    storageBucket: 'royale-moments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtK9vUjWjhi252xqq-L4iwiX9xIgpSB-w',
    appId: '1:63605957686:ios:d9d71ef07269442199a497',
    messagingSenderId: '63605957686',
    projectId: 'royale-moments',
    storageBucket: 'royale-moments.firebasestorage.app',
    iosBundleId: 'com.example.eidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtK9vUjWjhi252xqq-L4iwiX9xIgpSB-w',
    appId: '1:63605957686:ios:d9d71ef07269442199a497',
    messagingSenderId: '63605957686',
    projectId: 'royale-moments',
    storageBucket: 'royale-moments.firebasestorage.app',
    iosBundleId: 'com.example.eidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNVJeid3Vw2idupTrQvChy_Fl0tu-YSSU',
    appId: '1:63605957686:web:cd70f318307457d999a497',
    messagingSenderId: '63605957686',
    projectId: 'royale-moments',
    authDomain: 'royale-moments.firebaseapp.com',
    storageBucket: 'royale-moments.firebasestorage.app',
    measurementId: 'G-X9LDM1Y1SM',
  );
}
